title: Shane O Neill's blog
description: > # this means to ignore newlines until "baseurl:"
  Feb 25th 2020: This blog is a work in progress.
permalink: ':title/'
# baseurl: "" # the subpath of your site, e.g. /blog
url: "shaneodub.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Shane O Neill # add your name
author-img: shane-o-neill.jpg # add your photo
about-author: Short data analytics articles. Blog is under construction. 25/02/2020  # add description
social-twitter: shaneodub # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: shaneodub # add your Github handle
social-linkedin: shaneodub # add your Linkedin handle
social-email: shaneodub@gmail.com # add your Email address

# Disqus
# discus-identifier: mr-brown # add your discus identifier

# Tracker
google_analytics: UA-159060552-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
